sonar.projectKey=maylisl-openclassrooms
sonar.organization=MaylisL
sonar.host.url=${env.SONAR_HOST_URL}

# Source directories
sonar.sources=back/src/main/java,front/src

# Tests directories
sonar.tests=back/src/test/java,front/src

# Languages
sonar.java.binaries=back/target/classes

# Coverage
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=back/target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8
